#43 retro lambda merge di dagger
Nimtego/ofc pull request #45
Opened 2018-08-13 21:42 UTC by Nimtego

#43 #44 связал вроде. чекни. Ишью задним числом сделаю.

2018-08-14 09:00 UTC, Reeson2003 requested changes

2018-08-14 09:00 UTC, Reeson2003 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK" />
удоли это

2018-08-14 09:00 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/component/DatabaseModule.java
> +        return DBHelperStub.getInstance();
Тут даггер сам не делает синглтон разве? Мб не надо getInstance брать просто через new?

2018-08-14 09:00 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/service/DBHelperStub.java
> +                    instance = new DBHelperStub();
Не надо синглтон, надо инжект даггером

2018-08-14 09:23 UTC, Nimtego commented on app/src/main/java/com/example/pto6/ofc/component/DatabaseModule.java
> +        return DBHelperStub.getInstance();
Удаленная строка это тот стаб который был не сиглтоном. Есть вариант поместить @Singleton Scope аннотацию  Даггер будет предоставлять этот единственный экземпляр. Таким образом можно отказаться в принципе от создания самостоятельных синглтонов и переложить это на даггер он сам сгенерит.

2018-08-14 09:24 UTC, Nimtego commented on app/src/main/java/com/example/pto6/ofc/service/DBHelperStub.java
> +                    instance = new DBHelperStub();
Выше описал изменения. Делегировать даггеру задачу. То есть отказываемся от синглтонов в принципе?

2018-08-14 09:25 UTC, Nimtego commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK" />
.idea какжешь ты ...

2018-08-14 09:50 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/component/DatabaseModule.java
> +        return DBHelperStub.getInstance();
Я это и имел в виду

2018-08-14 09:51 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/service/DBHelperStub.java
> +                    instance = new DBHelperStub();
да

2018-08-14 19:42 UTC, Reeson2003 submitted a review, later dismissed
Немного почитал про  Dagger 2. Вроде все правильно.

2018-08-15 20:28 UTC, Reeson2003 approved these changes

2018-08-16 05:52 UTC, merged