Fixed update list debit credit
Nimtego/ofc pull request #58
Opened 2018-08-21 23:04 UTC by Nimtego

Fixes #56 

## Proposed Changes

  Fixed update list debit credit + fixed update list debit/credit

2018-08-22 05:44 UTC, Reeson2003 requested changes

2018-08-22 05:44 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/dto/CreditDTO.java
> +    }
Зачем геттеры/сеттеры? Есть же lombok.

2018-08-22 05:44 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/dto/DebitDTO.java
> +    }
См выше

2018-08-22 05:44 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/presenter/DataEntryPresenter.java
> +        if (dto instanceof DebitDTO) {
Как я понимаю, DataEntryPresenter это контроллер окна ввода данных. Оно одно для кредита и дебита. Странно, что этот контроллер знает, о том,  для какой сущности его используют.  instanceof говорит о том, что тут проблемы с архитектурой

2018-08-22 05:44 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/presenter/DataEntryPresenter.java
> +            Date change = new Date();
Зачем создаем 2 раза новую дату? Одной недостаточно?

2018-08-22 05:44 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/presenter/DataEntryPresenter.java
> +                    .build();
Дублирование кода для DebitDto CreditDto

2018-08-22 05:44 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/view/DataEntryActivity.java
> +            dto = mFragment.getDTO();
тут есть смысл чекать инстанс, если в конечном итоге мы делаем `dto = mFragment.getDTO();`? В любом случае дублирование кода надо убрать

2018-08-22 05:44 UTC, Reeson2003 commented on app/src/main/java/com/example/pto6/ofc/view/fragments/AddCreditFragment.java
> +    EditText amount;
Почему вмдимость package?

2018-08-22 17:24 UTC, Nimtego commented on app/src/main/java/com/example/pto6/ofc/view/fragments/AddCreditFragment.java
> +    EditText amount;
Butterknife как и даггер не используют приватные

2018-08-22 20:47 UTC, Nimtego commented on app/src/main/java/com/example/pto6/ofc/view/fragments/AddCreditFragment.java
> +    EditText amount;
error: @BindView fields must not be private or static. (com.example.pto6.ofc.view.OfcListActivity.tabs)

2018-08-23 04:46 UTC, Reeson2003 approved these changes
Аппрувлю, чтоб не висела ветка. Надо делать рефакторинг и переезжать на Event Bus.

2018-08-23 04:46 UTC, merged